openapi: "3.0.3"
info:
  description: "Hunspot Challenge API"
  version: "1.0.0"
  title: "Hubspot Challenge API"
servers:
  - url: https://localhost:8080/api/v1
    description: "local"

tags:
  - name: newrelic

paths:
  '/sessionData':
    post:
      deprecated: true
      tags:
        - hubspot
      summary: Get date from api process and sends data to another api
      operationId: getAndProcessData
      parameters:
        - name: userKey
          in: query
          required: true
          description: key
          schema:
            type: string
      responses:
        "200":
          description: OK
